name: docker
description: setup docker

runs:
  using: composite
  steps:
    # cache limit 5gb, so min not max https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
    # caching documentation https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
    # caching issue https://github.com/docker/build-push-action/issues/252
    - name: Cache docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker clear cache
      shell: bash
      # prune
      # - unlimited cache https://github.com/docker/build-push-action/issues/252
      # - docs https://docs.docker.com/engine/reference/commandline/image_prune/
      # - stale, insecure images https://devops.datenkollektiv.de/avoiding-stale-docker-images.html
      run: docker system prune --filter "until=32h" --force
