name: nodejs__aws-lambda-ric
on:
  push:
    branches:
      - "*"
  schedule:
    # rebuild every day at 1am UTC for security and updates
    - cron: "0 1 * * *"

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}__${{ github.workflow }}

jobs:
  setup:
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        timeout-minutes: 5
        uses: actions/checkout@v3

      - id: create_tag
        name: create tag
        timeout-minutes: 5
        uses: ./.github/composite/create-tag

      - name: create draft release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 5
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: ${{ steps.create_tag.outputs.tag }}
          draft: true
          prerelease: false
    timeout-minutes: 15

  build-and-upload:
    needs:
      - setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - public.ecr.aws/amazonlinux/amazonlinux:2022
          - public.ecr.aws/lts/ubuntu:jammy
        nodejs:
          - 14
          - 16
          - 18
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: checkout repository
        timeout-minutes: 5
        uses: actions/checkout@v3

      - name: setup docker
        timeout-minutes: 15
        uses: ./.github/composite/setup-docker

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - id: get-os
        name: get os
        timeout-minutes: 5
        uses: ./.github/composite/get-os
        with:
          IMAGE: ${{ matrix.image }}

      - id: get-architecture
        name: get architecture
        timeout-minutes: 5
        uses: ./.github/composite/get-architecture
        with:
          PLATFORM: ${{ matrix.platform }}

      - id: get-filenames
        name: get filenames
        timeout-minutes: 5
        env:
          OS: ${{ steps.get-os.outputs.os }}
          ARCHITECTURE: ${{ steps.get-architecture.outputs.architecture }}
          NODEJS_MAJOR_VERSION: ${{ matrix.nodejs }}
        run: |
          ric_filename="${OS:-}__${ARCHITECTURE:-}__nodejs-${NODEJS_MAJOR_VERSION:-}__aws-lambda-ric.tar.gz"
          vercel_ncc_ric_filename="${OS:-}__${ARCHITECTURE:-}__nodejs-${NODEJS_MAJOR_VERSION:-}__vercel-ncc-aws-lambda-ric.tar.gz"
          echo "::set-output name=ric_filename::$ric_filename"
          echo "::set-output name=vercel_ncc_ric_filename::$vercel_ncc_ric_filename"
          echo "$ric_filename"
          echo "$vercel_ncc_ric_filename"

      - name: compile
        shell: bash
        env:
          IMAGE: ${{ matrix.image }}
          OS: ${{ steps.get-os.outputs.os }}
          PLATFORM: ${{ matrix.platform }}
          NODEJS_MAJOR_VERSION: ${{ matrix.nodejs }}
          RIC_FILENAME: ${{ steps.get-filenames.outputs.ric_filename }}
          VERCEL_NCC_RIC_FILENAME: ${{ steps.get-filenames.outputs.vercel_ncc_ric_filename }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker run --platform "$PLATFORM" --env-file <(printenv) --entrypoint "/bin/bash" -v "$(pwd):/var/task" --rm "$IMAGE" -c "/var/task/bin/$OS/workflows/${{ github.workflow }}"

      - name: Upload ric
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ${{ steps.get-filenames.outputs.ric_filename }}
          asset_name: ${{ steps.get-filenames.outputs.ric_filename }}
          asset_content_type: application/gzip

      - name: Upload vercel_ncc_ric
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
        with:
          upload_url: ${{ needs.setup.outputs.upload_url }}
          asset_path: ${{ steps.get-filenames.outputs.vercel_ncc_ric_filename }}
          asset_name: ${{ steps.get-filenames.outputs.vercel_ncc_ric_filename }}
          asset_content_type: application/gzip

    # max timeout of 6 hours (60 minutes * 6)
    timeout-minutes: 360

  publish-release:
    needs:
      - setup
      - build-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: eregon/publish-release@v1
        timeout-minutes: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.setup.outputs.release_id }}
      - uses: eregon/keep-last-n-releases@v1
        timeout-minutes: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          n: 60
          remove_tags_without_release: true
