name: python__awslambdaric
on:
  push:
    branches:
      - "*"
  schedule:
    # rebuild every day at 1am UTC for security and updates
    - cron: "0 1 * * *"

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}__${{ github.workflow }}

jobs:
  should-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        timeout-minutes: 5
        uses: actions/checkout@v3
    timeout-minutes: 15
