name: python__awslambdaric
on:
  push:
    branches:
      - "*"
  schedule:
    # rebuild every day at 1am UTC for security and updates
    - cron: "0 1 * * *"

jobs:
  should-run:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.ref }}__${{ github.workflow }}__${{ github.job }}
    outputs:
      has-changed: ${{ toJSON(
        steps.changes.outputs.workflow == 'true' ||
        steps.changes.outputs.composite == 'true') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        timeout-minutes: 5
        uses: actions/checkout@v3

      - id: changes
        name: workflow file has changed
        timeout-minutes: 15
        uses: dorny/paths-filter@v2
        with:
          filters: |
            workflow:
              - '.github/workflows/${{ github.job }}.yml'
              - 'bin/*/workflows/${{ github.job }}.yml'
            composite:
              - '.github/composite/**'
              - 'bin/*/scripts/**'
    timeout-minutes: 15
